### ISSUE TITLE
WIP: spid-node

### ISSUE THREAD

**Issue by Takeno** [italia/spid-passport#2]
In relazione alla issue #1 e alla challenge di Hack.Developers.Italia, abbiamo iniziato lo sviluppo di un modulo node.js indipendente dal middleware di autorizzazione.

Il progetto si basa su `samlify` e offrirà una comoda API per creare nuove login request e fare il parsing delle risposte dei dati, fornendo una configurazione preimpostata per gli Identity Provider accreditati.

E' un WIP, non ancora utilizzabile:
https://github.com/Roma-JS/spid-node

**Comment by alranel** [comment]
Ciao @Takeno, qual è lo stato di questo lavoro? È utilizzabile? Pensate di lavorarci ancora?

**Comment by Takeno** [comment]
L'idea c'è, ma purtroppo non è utilizzabile in quanto non genera un XML valido. Possiamo chiudere questa issue. Internamente sappiamo di questo progetto e non appena qualcuno prenderà in carico lo sviluppo la riapriremo.

**Comment by alranel** [comment]
Ok @Takeno, allora chiudo. Nel frattempo ho mergiato l'altra pull request di @cicciodifranco che era più avanti e al momento funziona almeno per il login. Sarebbe bello se poteste collaborare unendo le forze. Ciao!
